/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interface;

import ClassesTables.Cliente;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Augusto Kalel
 */
public class CadastroCliente extends javax.swing.JFrame {

    /**
     * Creates new form CadastroCliente
     */
    public CadastroCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldCidade = new javax.swing.JTextField();
        jTextFieldNome = new javax.swing.JTextField();
        jTextFieldCPF = new javax.swing.JTextField();
        jTextFieldBairro = new javax.swing.JTextField();
        jTextFieldRua = new javax.swing.JTextField();
        jTextFieldTelefone = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jTextFieldNascimento = new javax.swing.JTextField();
        jTextFieldNumero = new javax.swing.JTextField();
        jToggleButtonCadastrar = new javax.swing.JToggleButton();
        jToggleButtonCancelar = new javax.swing.JToggleButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldUsuario = new javax.swing.JTextField();
        jPasswordFieldPass = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(380, 495));
        getContentPane().setLayout(null);

        jLabel1.setText("Nome:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 10, 31, 14);

        jLabel2.setText("CPF:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 40, 23, 14);

        jLabel3.setText("Rua:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 340, 23, 20);

        jLabel4.setText("Bairro:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 370, 40, 14);

        jLabel5.setText("Cidade:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 400, 37, 14);

        jLabel6.setText("Telefone:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 70, 46, 20);

        jLabel7.setText("E-mail:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 110, 32, 14);

        jLabel8.setText("data de nascimento:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 150, 98, 14);

        jLabel9.setText("NUmero:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(210, 340, 42, 20);

        jTextFieldCidade.setText("cidade");
        getContentPane().add(jTextFieldCidade);
        jTextFieldCidade.setBounds(70, 400, 100, 20);

        jTextFieldNome.setText("nome");
        getContentPane().add(jTextFieldNome);
        jTextFieldNome.setBounds(60, 10, 70, 20);

        jTextFieldCPF.setText("cpf");
        jTextFieldCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCPFActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldCPF);
        jTextFieldCPF.setBounds(50, 40, 120, 20);

        jTextFieldBairro.setText("bairro");
        getContentPane().add(jTextFieldBairro);
        jTextFieldBairro.setBounds(70, 370, 120, 20);

        jTextFieldRua.setText("rua");
        jTextFieldRua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRuaActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldRua);
        jTextFieldRua.setBounds(70, 340, 120, 20);

        jTextFieldTelefone.setText("telefone");
        jTextFieldTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTelefoneActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldTelefone);
        jTextFieldTelefone.setBounds(80, 70, 120, 30);

        jTextFieldEmail.setText("email");
        getContentPane().add(jTextFieldEmail);
        jTextFieldEmail.setBounds(70, 110, 130, 20);

        jTextFieldNascimento.setText("dataNasc");
        getContentPane().add(jTextFieldNascimento);
        jTextFieldNascimento.setBounds(130, 150, 70, 20);

        jTextFieldNumero.setText("numero");
        getContentPane().add(jTextFieldNumero);
        jTextFieldNumero.setBounds(270, 340, 69, 30);

        jToggleButtonCadastrar.setText("Cadastrar");
        jToggleButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButtonCadastrar);
        jToggleButtonCadastrar.setBounds(80, 450, 81, 23);

        jToggleButtonCancelar.setText("Cancelar");
        getContentPane().add(jToggleButtonCancelar);
        jToggleButtonCancelar.setBounds(190, 450, 75, 23);

        jLabel10.setText("Usuario:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(20, 200, 40, 14);

        jLabel11.setText("Senha:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(20, 230, 48, 14);

        jTextFieldUsuario.setText("usuario");
        getContentPane().add(jTextFieldUsuario);
        jTextFieldUsuario.setBounds(80, 200, 41, 20);

        jPasswordFieldPass.setText("jPasswordField1");
        getContentPane().add(jPasswordFieldPass);
        jPasswordFieldPass.setBounds(80, 230, 111, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonCadastrarActionPerformed
        setCampos();
        
    }//GEN-LAST:event_jToggleButtonCadastrarActionPerformed
        public void setCampos(){
           try{ Cliente cliente1 = new Cliente();
            cliente1.setNome (jTextFieldNome.getText());
            cliente1.setCPF (jTextFieldCPF.getText());
            cliente1.setEndereco(jTextFieldRua.getText());
            cliente1.setBairro(jTextFieldBairro.getText());
            cliente1.setCidade(jTextFieldCidade.getText());
            cliente1.setTelefone(jTextFieldTelefone.getText());
            cliente1.setEmail(jTextFieldEmail.getText());
            //converter String em Date
            SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
            cliente1.setDataNascimento(formatter.parse(jTextFieldNascimento.getText()));
           }catch(Exception e){
               JOptionPane.showMessageDialog(rootPane, "***Problemas ao cadastrar dados contate o administrador de sistemas" );
           }
        }
    private void jTextFieldCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCPFActionPerformed

    private void jTextFieldTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTelefoneActionPerformed

    private void jTextFieldRuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRuaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordFieldPass;
    private javax.swing.JTextField jTextFieldBairro;
    private javax.swing.JTextField jTextFieldCPF;
    private javax.swing.JTextField jTextFieldCidade;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldNascimento;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldNumero;
    private javax.swing.JTextField jTextFieldRua;
    private javax.swing.JTextField jTextFieldTelefone;
    private javax.swing.JTextField jTextFieldUsuario;
    private javax.swing.JToggleButton jToggleButtonCadastrar;
    private javax.swing.JToggleButton jToggleButtonCancelar;
    // End of variables declaration//GEN-END:variables
}
